# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        ('payments', '0001_initial'),
        ('segment', '0001_initial'),
        ('vendor_bills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='vendor_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='vendor_bills.vendorbill'),
        ),
        migrations.AddField(
            model_name='taxcomponent',
            name='gl_account',
            field=models.ForeignKey(help_text='GL account for this tax component', on_delete=django.db.models.deletion.PROTECT, related_name='tax_components', to='segment.xx_segment'),
        ),
        migrations.AddField(
            model_name='taxjurisdiction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AddField(
            model_name='taxperiod',
            name='filed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_tax_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxperiod',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_period', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='taxperiod',
            name='jurisdiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_periods', to='payments.taxjurisdiction'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='jurisdiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='payments.taxjurisdiction'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='tax_payable_account',
            field=models.ForeignKey(help_text='Tax payable GL account', on_delete=django.db.models.deletion.PROTECT, related_name='tax_payable_rates', to='segment.xx_segment'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='tax_receivable_account',
            field=models.ForeignKey(blank=True, help_text='Tax receivable GL account (for reverse charge)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_receivable_rates', to='segment.xx_segment'),
        ),
        migrations.AddField(
            model_name='taxcomponent',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payments.taxrate'),
        ),
        migrations.AddIndex(
            model_name='appaymentbatch',
            index=models.Index(fields=['status', 'batch_date'], name='payment_int_status_b0beb5_idx'),
        ),
        migrations.AddIndex(
            model_name='appaymentbatch',
            index=models.Index(fields=['payment_date', 'status'], name='payment_int_payment_3a61b6_idx'),
        ),
        migrations.AddIndex(
            model_name='appaymentbatch',
            index=models.Index(fields=['is_reconciled', 'status'], name='payment_int_is_reco_c7d0e1_idx'),
        ),
        migrations.AddIndex(
            model_name='appaymentline',
            index=models.Index(fields=['ap_invoice', 'is_paid'], name='payments_ap_ap_invo_ae270c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appaymentline',
            unique_together={('payment_batch', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='corporatetaxaccrual',
            index=models.Index(fields=['fiscal_year', 'period_quarter'], name='payments_co_fiscal__c35361_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatetaxaccrual',
            index=models.Index(fields=['is_posted'], name='payments_co_is_post_9f8131_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='corporatetaxaccrual',
            unique_together={('fiscal_year', 'period_month')},
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['status', 'requested_payment_date'], name='payment_int_status_42ae09_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['supplier', 'status'], name='payment_int_supplie_c52dba_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['priority', 'status'], name='payment_int_priorit_656c87_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['payment_batch'], name='payment_int_payment_49c40b_idx'),
        ),
        migrations.AddIndex(
            model_name='taxperiod',
            index=models.Index(fields=['jurisdiction', 'status'], name='payments_ta_jurisdi_d0ad4c_idx'),
        ),
        migrations.AddIndex(
            model_name='taxperiod',
            index=models.Index(fields=['period_end', 'status'], name='payments_ta_period__0332f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxperiod',
            unique_together={('jurisdiction', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['jurisdiction', 'rate_type', 'is_active'], name='payments_ta_jurisdi_84016e_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['rate_code', 'is_active'], name='payments_ta_rate_co_ba6148_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxrate',
            unique_together={('jurisdiction', 'rate_code')},
        ),
        migrations.AlterUniqueTogether(
            name='taxcomponent',
            unique_together={('tax_rate', 'component_type')},
        ),
    ]
