# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_session', models.CharField(blank=True, db_index=True, help_text='Temporary session ID for files uploaded during document creation', max_length=100, null=True)),
                ('is_temporary', models.BooleanField(default=False, help_text='True if file is temporarily stored and not yet linked to a document')),
                ('file', models.FileField(help_text='Allowed file types: PDF, Word, Excel, Images, Text, ZIP', max_length=500, upload_to='procurement/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'csv', 'jpg', 'jpeg', 'png', 'gif', 'zip', 'rar'])])),
                ('document_type', models.CharField(choices=[('PO', 'Purchase Order'), ('PR', 'Purchase Requisition'), ('QUOTE', 'Vendor Quote'), ('CONTRACT', 'Contract'), ('SPEC', 'Specification'), ('OTHER', 'Other')], default='OTHER', help_text='Type/category of the document', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Brief description of the attachment', max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('original_filename', models.CharField(blank=True, help_text='Original filename when uploaded', max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'procurement_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
