# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement_attachments', '0001_initial'),
        ('purchase_orders', '0001_initial'),
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='po_header',
            field=models.ForeignKey(blank=True, help_text='Related Purchase Order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchase_orders.poheader'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='pr_header',
            field=models.ForeignKey(blank=True, help_text='Related Purchase Requisition', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requisitions.prheader'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['po_header', '-uploaded_at'], name='procurement_po_head_4749a6_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['pr_header', '-uploaded_at'], name='procurement_pr_head_51b392_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['temp_session', 'is_temporary'], name='procurement_temp_se_586de7_idx'),
        ),
    ]
