# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('segment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(default='$', max_length=8)),
                ('is_base', models.BooleanField(default=False, help_text='Is this the base/home currency?')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FXGainLossAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gain_loss_type', models.CharField(choices=[('REALIZED_GAIN', 'Realized FX Gain'), ('REALIZED_LOSS', 'Realized FX Loss'), ('UNREALIZED_GAIN', 'Unrealized FX Gain'), ('UNREALIZED_LOSS', 'Unrealized FX Loss')], max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fx_config', to='segment.xx_segment')),
            ],
            options={
                'verbose_name': 'FX Gain/Loss Account',
                'verbose_name_plural': 'FX Gain/Loss Accounts',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCurrency',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=3)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(default='$', max_length=8)),
                ('is_base', models.BooleanField(default=False, help_text='Is this the base/home currency?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical currency',
                'verbose_name_plural': 'historical Currencies',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExchangeRate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rate_date', models.DateField(db_index=True, help_text='Date this rate is effective')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate (1 from_currency = rate * to_currency)', max_digits=18)),
                ('rate_type', models.CharField(choices=[('SPOT', 'Spot Rate'), ('AVERAGE', 'Average Rate'), ('FIXED', 'Fixed Rate'), ('CLOSING', 'Period Closing Rate')], default='SPOT', max_length=16)),
                ('source', models.CharField(blank=True, help_text='Source of rate (e.g., Central Bank, Manual)', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('from_currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.currency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.currency')),
            ],
            options={
                'verbose_name': 'historical exchange rate',
                'verbose_name_plural': 'historical exchange rates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTaxRate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Percent (e.g. 5 = 5%)', max_digits=6)),
                ('country', models.CharField(choices=[('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('EG', 'Egypt'), ('IN', 'India')], default='AE', max_length=2)),
                ('category', models.CharField(choices=[('STANDARD', 'Standard'), ('ZERO', 'Zero Rated'), ('EXEMPT', 'Exempt'), ('RC', 'Reverse Charge')], default='STANDARD', max_length=16)),
                ('code', models.CharField(blank=True, help_text='Display code (e.g., VAT5, GST18)', max_length=16)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this rate currently active?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tax rate',
                'verbose_name_plural': 'historical tax rates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Percent (e.g. 5 = 5%)', max_digits=6)),
                ('country', models.CharField(choices=[('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('EG', 'Egypt'), ('IN', 'India')], default='AE', max_length=2)),
                ('category', models.CharField(choices=[('STANDARD', 'Standard'), ('ZERO', 'Zero Rated'), ('EXEMPT', 'Exempt'), ('RC', 'Reverse Charge')], default='STANDARD', max_length=16)),
                ('code', models.CharField(blank=True, help_text='Display code (e.g., VAT5, GST18)', max_length=16)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this rate currently active?')),
            ],
            options={
                'ordering': ['country', '-effective_from'],
                'indexes': [models.Index(fields=['country', 'category', 'code', 'effective_from', 'effective_to'], name='core_taxrat_country_f2559b_idx')],
                'unique_together': {('country', 'category', 'code', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(db_index=True, help_text='Date this rate is effective')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate (1 from_currency = rate * to_currency)', max_digits=18)),
                ('rate_type', models.CharField(choices=[('SPOT', 'Spot Rate'), ('AVERAGE', 'Average Rate'), ('FIXED', 'Fixed Rate'), ('CLOSING', 'Period Closing Rate')], default='SPOT', max_length=16)),
                ('source', models.CharField(blank=True, help_text='Source of rate (e.g., Central Bank, Manual)', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_from', to='core.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_to', to='core.currency')),
            ],
            options={
                'ordering': ['-rate_date', 'from_currency', 'to_currency'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', '-rate_date'], name='core_exchan_from_cu_27b99e_idx'), models.Index(fields=['rate_date', 'is_active'], name='core_exchan_rate_da_f70f5a_idx')],
                'unique_together': {('from_currency', 'to_currency', 'rate_date', 'rate_type')},
            },
        ),
    ]
