# Generated by Django 5.2.7 on 2025-10-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxrate',
            name='category',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('ZERO', 'Zero Rated'), ('EXEMPT', 'Exempt'), ('RC', 'Reverse Charge')], default='STANDARD', max_length=16),
        ),
        migrations.AddField(
            model_name='historicaltaxrate',
            name='code',
            field=models.CharField(blank=True, help_text='Display code (e.g., VAT5, GST18)', max_length=16),
        ),
        migrations.AddField(
            model_name='historicaltaxrate',
            name='country',
            field=models.CharField(choices=[('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('EG', 'Egypt'), ('IN', 'India')], default='AE', max_length=2),
        ),
        migrations.AddField(
            model_name='historicaltaxrate',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='category',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('ZERO', 'Zero Rated'), ('EXEMPT', 'Exempt'), ('RC', 'Reverse Charge')], default='STANDARD', max_length=16),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='code',
            field=models.CharField(blank=True, help_text='Display code (e.g., VAT5, GST18)', max_length=16),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='country',
            field=models.CharField(choices=[('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('EG', 'Egypt'), ('IN', 'India')], default='AE', max_length=2),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltaxrate',
            name='rate',
            field=models.DecimalField(decimal_places=3, help_text='Percent (e.g. 5 = 5%)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='rate',
            field=models.DecimalField(decimal_places=3, help_text='Percent (e.g. 5 = 5%)', max_digits=6),
        ),
    ]
