# Generated by Django 5.2.7 on 2025-10-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicaltaxrate_category_historicaltaxrate_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxrate',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['country', 'category', 'code', 'effective_from', 'effective_to'], name='core_taxrat_country_f2559b_idx'),
        ),
    ]
