# Generated by Django 5.2.7 on 2025-10-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicaltaxrate_effective_to_taxrate_effective_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='historicalcurrency',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical currency', 'verbose_name_plural': 'historical Currencies'},
        ),
        migrations.AlterModelOptions(
            name='taxrate',
            options={'ordering': ['country', '-effective_from']},
        ),
        migrations.AddField(
            model_name='currency',
            name='is_base',
            field=models.BooleanField(default=False, help_text='Is this the base/home currency?'),
        ),
        migrations.AddField(
            model_name='historicalcurrency',
            name='is_base',
            field=models.BooleanField(default=False, help_text='Is this the base/home currency?'),
        ),
        migrations.AddField(
            model_name='historicaltaxrate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this rate currently active?'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this rate currently active?'),
        ),
    ]
