# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ar', '0001_initial'),
        ('core', '0001_initial'),
        ('periods', '__first__'),
        ('segment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateTaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('AE', 'UAE'), ('SA', 'KSA'), ('EG', 'Egypt'), ('IN', 'India')], max_length=2)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Percent, e.g., 9 = 9%', max_digits=6)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Optional profit threshold for tax applicability', max_digits=16, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('account_code', models.CharField(blank=True, max_length=32)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('swift', models.CharField(blank=True, max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBankAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('account_code', models.CharField(blank=True, max_length=32)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('swift', models.CharField(blank=True, max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.currency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bank account',
                'verbose_name_plural': 'historical bank accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCorporateTaxRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('country', models.CharField(choices=[('AE', 'UAE'), ('SA', 'KSA'), ('EG', 'Egypt'), ('IN', 'India')], max_length=2)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Percent, e.g., 9 = 9%', max_digits=6)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Optional profit threshold for tax applicability', max_digits=16, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical corporate tax rule',
                'verbose_name_plural': 'historical corporate tax rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalJournalEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('posted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.currency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, db_constraint=False, help_text='Fiscal period for this journal entry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='periods.fiscalperiod')),
            ],
            options={
                'verbose_name': 'historical journal entry',
                'verbose_name_plural': 'historical journal entrys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=16)),
                ('invoice_no', models.CharField(max_length=64, unique=True)),
                ('currency', models.CharField(max_length=8)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ar.customer')),
                ('reversal_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='finance.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('AR', 'AR Invoice'), ('AP', 'AP Invoice')], max_length=2)),
                ('invoice_id', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTED', 'Posted')], default='PENDING_APPROVAL', max_length=20)),
                ('submitted_by', models.CharField(help_text='User who submitted for approval', max_length=128)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.CharField(blank=True, help_text='User who approved/rejected', max_length=128)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, help_text='Approval/rejection comments')),
                ('approval_level', models.IntegerField(default=1, help_text='Level in multi-level approval chain')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['invoice_type', 'invoice_id'], name='finance_inv_invoice_ae69ec_idx'), models.Index(fields=['status'], name='finance_inv_status_96501f_idx')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('posted', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('period', models.ForeignKey(blank=True, help_text='Fiscal period for this journal entry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='periods.fiscalperiod')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCorporateTaxFiling',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('country', models.CharField(choices=[('AE', 'UAE'), ('SA', 'KSA'), ('EG', 'Egypt'), ('IN', 'India')], max_length=2)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACCRUED', 'Accrued'), ('FILED', 'Filed (locked)'), ('REVERSED', 'Reversed')], default='ACCRUED', max_length=16)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('accrual_journal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.journalentry')),
                ('reversal_journal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.journalentry')),
            ],
            options={
                'verbose_name': 'historical corporate tax filing',
                'verbose_name_plural': 'historical corporate tax filings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CorporateTaxFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('AE', 'UAE'), ('SA', 'KSA'), ('EG', 'Egypt'), ('IN', 'India')], max_length=2)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACCRUED', 'Accrued'), ('FILED', 'Filed (locked)'), ('REVERSED', 'Reversed')], default='ACCRUED', max_length=16)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('accrual_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corp_tax_accrual', to='finance.journalentry')),
                ('reversal_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corp_tax_reversal', to='finance.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='segment.xx_segment')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='JournalLineSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='finance.journalline')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='segment.xx_segment')),
                ('segment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='segment.xx_segmenttype')),
            ],
            options={
                'db_table': 'JOURNAL_LINE_SEGMENT',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('amount_net', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_gross', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='segment.xx_segment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.invoice')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.taxcode')),
            ],
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'customer'], name='finance_inv_status_62187b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='corporatetaxfiling',
            unique_together={('country', 'period_start', 'period_end', 'organization_id')},
        ),
        migrations.AddIndex(
            model_name='journallinesegment',
            index=models.Index(fields=['journal_line', 'segment_type'], name='JOURNAL_LIN_journal_3b34c4_idx'),
        ),
        migrations.AddIndex(
            model_name='journallinesegment',
            index=models.Index(fields=['segment'], name='JOURNAL_LIN_segment_5fd1a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journallinesegment',
            unique_together={('journal_line', 'segment_type')},
        ),
    ]
