# Generated by Django 5.2.7 on 2025-11-11 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0003_initial'),
        ('ar', '0002_initial'),
        ('finance', '0001_initial'),
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule name/description', max_length=255)),
                ('priority', models.IntegerField(default=100, help_text='Lower number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('account_segment', models.ForeignKey(help_text='When this account is used, apply these segment assignments', on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules_for_account', to='segment.xx_segment')),
                ('cost_center_segment', models.ForeignKey(blank=True, help_text='Cost center to assign', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules_cc', to='segment.xx_segment')),
                ('customer', models.ForeignKey(blank=True, help_text='Apply to specific customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='ar.customer')),
                ('department_segment', models.ForeignKey(blank=True, help_text='Department to assign', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules_dept', to='segment.xx_segment')),
                ('product_segment', models.ForeignKey(blank=True, help_text='Product to assign', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules_prod', to='segment.xx_segment')),
                ('project_segment', models.ForeignKey(blank=True, help_text='Project to assign', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules_proj', to='segment.xx_segment')),
                ('supplier', models.ForeignKey(blank=True, help_text='Apply to specific supplier', null=True, on_delete=django.db.models.deletion.CASCADE, to='ap.supplier')),
            ],
            options={
                'db_table': 'finance_segment_assignment_rule',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='finance_seg_is_acti_111fef_idx'), models.Index(fields=['customer', 'account_segment'], name='finance_seg_custome_6e7682_idx'), models.Index(fields=['supplier', 'account_segment'], name='finance_seg_supplie_6424f0_idx')],
            },
        ),
    ]
