# Generated by Django 5.2.7 on 2025-10-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apinvoice',
            name='gl_journal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_source', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='gl_journal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_source', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
