# Generated by Django 5.2.7 on 2025-11-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_segmentassignmentrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='tax_code',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceLine',
        ),
        migrations.DeleteModel(
            name='TaxCode',
        ),
    ]
