# Generated by Django 5.2.7 on 2025-10-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_apinvoice_paid_at_appayment_gl_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appayment',
            name='reconciled_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='reconciled_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
