# Generated by Django 5.2.7 on 2025-10-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_appayment_reconciled_at_arpayment_reconciled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appayment',
            name='gl_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AlterField(
            model_name='arpayment',
            name='gl_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
    ]
