# Generated by Django 5.2.7 on 2025-10-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_appayment_gl_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appayment',
            name='payment_fx_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='payment_fx_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
