# Generated by Django 5.2.7 on 2025-10-08 10:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_corporatetaxrule_historicalcorporatetaxrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apitem',
            name='tax_category',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('ZERO', 'Zero'), ('EXEMPT', 'Exempt'), ('RC', 'Reverse Charge')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='apitem',
            name='tax_country',
            field=models.CharField(blank=True, choices=[('AE', 'UAE'), ('SA', 'KSA'), ('EG', 'Egypt'), ('IN', 'India')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='aritem',
            name='tax_category',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('ZERO', 'Zero'), ('EXEMPT', 'Exempt'), ('RC', 'Reverse Charge')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='aritem',
            name='tax_country',
            field=models.CharField(blank=True, choices=[('AE', 'UAE'), ('SA', 'KSA'), ('EG', 'Egypt'), ('IN', 'India')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalCorporateTaxFiling',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('country', models.CharField(choices=[('AE', 'UAE'), ('SA', 'KSA'), ('EG', 'Egypt'), ('IN', 'India')], max_length=2)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACCRUED', 'Accrued'), ('FILED', 'Filed (locked)'), ('REVERSED', 'Reversed')], default='ACCRUED', max_length=16)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('accrual_journal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.journalentry')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reversal_journal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.journalentry')),
            ],
            options={
                'verbose_name': 'historical corporate tax filing',
                'verbose_name_plural': 'historical corporate tax filings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CorporateTaxFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('AE', 'UAE'), ('SA', 'KSA'), ('EG', 'Egypt'), ('IN', 'India')], max_length=2)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACCRUED', 'Accrued'), ('FILED', 'Filed (locked)'), ('REVERSED', 'Reversed')], default='ACCRUED', max_length=16)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('accrual_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corp_tax_accrual', to='finance.journalentry')),
                ('reversal_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corp_tax_reversal', to='finance.journalentry')),
            ],
            options={
                'unique_together': {('country', 'period_start', 'period_end', 'organization_id')},
            },
        ),
    ]
