# Generated by Django 5.2.7 on 2025-10-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_invoice_db_guards'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='ck_invoice_totals_nonnegative',
        ),
    ]
