# Generated by Django 5.2.7 on 2025-10-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_currency_options_and_more'),
        ('finance', '0011_remove_invoice_ck_invoice_totals_nonnegative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this account active?'),
        ),
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, help_text='Unique customer code', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='AE', help_text='ISO 2-letter country code', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(blank=True, help_text="Customer's default currency", null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT/Tax registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this account active?'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, help_text='Unique supplier code', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='AE', help_text='ISO 2-letter country code', max_length=2),
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.ForeignKey(blank=True, help_text="Supplier's default currency", null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT/Tax registration number', max_length=50),
        ),
    ]
