# Generated by Django 5.2.7 on 2025-10-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_account_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appayment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='apitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='apitem',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='appayment',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='appayment',
            name='gl_journal',
        ),
        migrations.RemoveField(
            model_name='arinvoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='arinvoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='arinvoice',
            name='gl_journal',
        ),
        migrations.RemoveField(
            model_name='aritem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='arpayment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='aritem',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='arpayment',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='arpayment',
            name='gl_journal',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='currency',
        ),
        migrations.DeleteModel(
            name='APInvoice',
        ),
        migrations.DeleteModel(
            name='APItem',
        ),
        migrations.DeleteModel(
            name='APPayment',
        ),
        migrations.DeleteModel(
            name='ARInvoice',
        ),
        migrations.DeleteModel(
            name='ARItem',
        ),
        migrations.DeleteModel(
            name='ARPayment',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
