# Generated by Django 5.2.7 on 2025-10-12 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0001_initial'),
        ('finance', '0013_remove_ar_ap_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ar.customer'),
        ),
    ]
