# Generated by Django 5.2.7 on 2025-10-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_invoice_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('AR', 'AR Invoice'), ('AP', 'AP Invoice')], max_length=2)),
                ('invoice_id', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTED', 'Posted')], default='PENDING_APPROVAL', max_length=20)),
                ('submitted_by', models.CharField(help_text='User who submitted for approval', max_length=128)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.CharField(blank=True, help_text='User who approved/rejected', max_length=128)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, help_text='Approval/rejection comments')),
                ('approval_level', models.IntegerField(default=1, help_text='Level in multi-level approval chain')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['invoice_type', 'invoice_id'], name='finance_inv_invoice_ae69ec_idx'), models.Index(fields=['status'], name='finance_inv_status_96501f_idx')],
            },
        ),
    ]
