# Generated by Django 5.2.7 on 2025-11-08 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Fiscal year (e.g., 2025)', unique=True)),
                ('start_date', models.DateField(help_text='First day of fiscal year')),
                ('end_date', models.DateField(help_text='Last day of fiscal year')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Additional notes about this fiscal year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fiscal_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'db_table': 'periods_fiscal_year',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField(help_text='Period number within fiscal year (1-12 for monthly)')),
                ('period_code', models.CharField(help_text='Unique code (e.g., 2025-01, 2025-Q1)', max_length=20, unique=True)),
                ('period_name', models.CharField(help_text='Display name (e.g., January 2025)', max_length=100)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('ADJUSTMENT', 'Adjustment')], default='MONTHLY', max_length=20)),
                ('start_date', models.DateField(help_text='First day of period')),
                ('end_date', models.DateField(help_text='Last day of period')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('is_adjustment_period', models.BooleanField(default=False, help_text='True for year-end adjustment periods')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_periods', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='periods.fiscalyear')),
            ],
            options={
                'verbose_name': 'Fiscal Period',
                'verbose_name_plural': 'Fiscal Periods',
                'db_table': 'periods_fiscal_period',
                'ordering': ['fiscal_year__year', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='PeriodStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=10)),
                ('new_status', models.CharField(max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True, help_text='Reason for status change')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_status_changes', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='periods.fiscalperiod')),
            ],
            options={
                'verbose_name': 'Period Status History',
                'verbose_name_plural': 'Period Status Histories',
                'db_table': 'periods_period_status',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['year'], name='periods_fis_year_626497_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['status'], name='periods_fis_status_bf8b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['fiscal_year', 'period_number'], name='periods_fis_fiscal__49ac74_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['period_code'], name='periods_fis_period__b81fef_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['status'], name='periods_fis_status_38190f_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='periods_fis_start_d_0e206c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('fiscal_year', 'period_number', 'period_type')},
        ),
        migrations.AddIndex(
            model_name='periodstatus',
            index=models.Index(fields=['fiscal_period', '-changed_at'], name='periods_per_fiscal__da0f74_idx'),
        ),
    ]
