# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XX_SegmentType',
            fields=[
                ('segment_id', models.IntegerField(help_text='Unique segment identifier', primary_key=True, serialize=False)),
                ('segment_name', models.CharField(help_text="Display name (e.g., 'Entity', 'Account', 'Project')", max_length=50, unique=True)),
                ('segment_type', models.CharField(help_text="Technical type (e.g., 'cost_center', 'account', 'project')", max_length=50)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this segment is required in transactions')),
                ('has_hierarchy', models.BooleanField(default=False, help_text='Whether this segment supports parent-child relationships')),
                ('length', models.IntegerField(default=50, help_text='Fixed code length for this segment (all codes must be this length)')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying in UI (lower = first)')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this segment represents', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this segment is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segment Type',
                'verbose_name_plural': 'Segment Types',
                'db_table': 'XX_SEGMENT_TYPE_XX',
                'ordering': ['display_order', 'segment_id'],
            },
        ),
        migrations.CreateModel(
            name='XX_Segment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='The actual segment code/value', max_length=50)),
                ('parent_code', models.CharField(blank=True, help_text='Parent segment code for hierarchical segments', max_length=50, null=True)),
                ('alias', models.CharField(blank=True, help_text='Display name / description', max_length=255, null=True)),
                ('node_type', models.CharField(choices=[('parent', 'Parent'), ('sub_parent', 'Sub-Parent'), ('child', 'Child')], default='child', help_text='Node type in hierarchy: parent (root), sub_parent (intermediate), or child (leaf)', max_length=20)),
                ('level', models.IntegerField(default=0, help_text='Hierarchy level (0 = root)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this segment value is active')),
                ('envelope_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Envelope/budget limit for this segment (if applicable)', max_digits=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment_type', models.ForeignKey(help_text='Which segment type this value belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='segment.xx_segmenttype')),
            ],
            options={
                'verbose_name': 'Segment Value',
                'verbose_name_plural': 'Segment Values',
                'db_table': 'XX_SEGMENT_XX',
                'indexes': [models.Index(fields=['segment_type', 'code'], name='XX_SEGMENT__segment_74fd90_idx'), models.Index(fields=['segment_type', 'parent_code'], name='XX_SEGMENT__segment_05aa6d_idx'), models.Index(fields=['code'], name='XX_SEGMENT__code_fd0bec_idx')],
                'unique_together': {('segment_type', 'code')},
            },
        ),
    ]
