# Generated by Django 5.2.7 on 2025-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_segmenttype',
            name='segment_id',
            field=models.AutoField(help_text='Unique segment identifier', primary_key=True, serialize=False),
        ),
    ]
