# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceGLLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ar_invoiceglline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ARItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_country', models.CharField(blank=True, choices=[('AE', 'UAE'), ('SA', 'KSA'), ('EG', 'Egypt'), ('IN', 'India')], max_length=2, null=True)),
                ('tax_category', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('ZERO', 'Zero'), ('EXEMPT', 'Exempt'), ('RC', 'Reverse Charge')], max_length=16, null=True)),
            ],
            options={
                'db_table': 'ar_aritem',
            },
        ),
        migrations.CreateModel(
            name='ARPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Payment reference number', max_length=64, null=True, unique=True)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total payment amount', max_digits=14, null=True)),
                ('memo', models.CharField(blank=True, help_text='Payment memo/notes', max_length=255)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled', models.BooleanField(default=False)),
                ('reconciliation_ref', models.CharField(blank=True, max_length=64)),
                ('reconciled_at', models.DateField(blank=True, null=True)),
                ('payment_fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate from invoice currency to payment currency (for FX gain/loss)', max_digits=18, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='DEPRECATED: Use total_amount instead', max_digits=14, null=True)),
            ],
            options={
                'db_table': 'ar_arpayment',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ARPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount allocated to this invoice', max_digits=14)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate from invoice currency to payment currency at allocation time', max_digits=18, null=True)),
            ],
            options={
                'db_table': 'ar_arpaymentallocation',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Unique customer code', max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(default='AE', help_text='ISO 2-letter country code', max_length=2)),
                ('vat_number', models.CharField(blank=True, help_text='VAT/Tax registration number', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ar_customer',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ARInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('country', models.CharField(choices=[('AE', 'UAE'), ('SA', 'KSA'), ('EG', 'Egypt'), ('IN', 'India')], default='AE', help_text='Tax country for this invoice (defaults to customer country)', max_length=2)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Approval workflow status', max_length=20)),
                ('is_posted', models.BooleanField(default=False, help_text='Whether invoice is posted to GL')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', help_text='Payment status of the invoice', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False, help_text='Whether invoice is cancelled')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate used when posting (invoice currency to base currency)', max_digits=18, null=True)),
                ('base_currency_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount in base currency', max_digits=14, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice subtotal (before tax)', max_digits=14, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total tax amount', max_digits=14, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice total (subtotal + tax)', max_digits=14, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_invoices', to='core.currency')),
            ],
            options={
                'db_table': 'ar_arinvoice',
            },
        ),
    ]
