# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ar', '0001_initial'),
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        ('periods', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='arinvoice',
            name='gl_journal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_source_new', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Fiscal period for this invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_invoices', to='periods.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='aritem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ar.arinvoice'),
        ),
        migrations.AddField(
            model_name='aritem',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_items', to='core.taxrate'),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_payments', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Payment currency (currency received)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_payments_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='gl_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_payment_source_new', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use allocations instead', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_legacy', to='ar.arinvoice'),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the invoice(s) being paid - for FX tracking', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_payments_invoice_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Fiscal period for this payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_payments', to='periods.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='arpaymentallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='ar.arinvoice'),
        ),
        migrations.AddField(
            model_name='arpaymentallocation',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the invoice (copied from invoice at allocation time)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_payment_allocations_invoice_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='arpaymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ar.arpayment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(blank=True, help_text="Customer's default currency", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_customers', to='core.currency'),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer making the payment', null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.customer'),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ar.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='arpaymentallocation',
            unique_together={('payment', 'invoice')},
        ),
    ]
