# Generated by Django 5.2.7 on 2025-11-13 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0002_initial'),
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceglline',
            options={},
        ),
        migrations.CreateModel(
            name='ARInvoiceDistributionSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_line', models.ForeignKey(db_column='distribution_id', help_text='FK to distribution line', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='ar.invoiceglline')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='segment.xx_segment')),
                ('segment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='segment.xx_segmenttype')),
            ],
            options={
                'db_table': 'ar_invoice_distribution_segment',
                'unique_together': {('gl_line', 'segment_type')},
            },
        ),
    ]
