# Generated by Django 5.2.7 on 2025-11-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0003_alter_invoiceglline_options_and_more'),
    ]

    operations = [
    ]
