# Generated by Django 5.2.7 on 2025-11-13 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0004_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceglline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distribution amount', max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceglline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceglline',
            name='description',
            field=models.CharField(blank=True, help_text='Distribution description', max_length=500),
        ),
        migrations.AddField(
            model_name='invoiceglline',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gl_lines', to='ar.arinvoice'),
        ),
        migrations.AddField(
            model_name='invoiceglline',
            name='line_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', help_text='Debit or Credit', max_length=50),
        ),
        migrations.AddField(
            model_name='invoiceglline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='invoiceglline',
            table='ar_invoice_distribution',
        ),
    ]
