# Generated by Django 5.2.7 on 2025-10-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0004_migrate_status_to_new_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arinvoice',
            name='status',
        ),
    ]
