# Generated by Django 5.2.7 on 2025-11-20 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0005_invoiceglline_amount_invoiceglline_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceglline',
            name='invoice',
            field=models.ForeignKey(default='na', on_delete=django.db.models.deletion.CASCADE, related_name='gl_lines', to='ar.arinvoice'),
            preserve_default=False,
        ),
    ]
