# Generated by Django 5.2.7 on 2025-10-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0005_remove_arinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arinvoice',
            name='country',
            field=models.CharField(choices=[('AE', 'UAE'), ('SA', 'KSA'), ('EG', 'Egypt'), ('IN', 'India')], default='AE', help_text='Tax country for this invoice (defaults to customer country)', max_length=2),
        ),
    ]
