# Generated by Django 5.2.7 on 2025-10-15 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0007_arpayment_memo'),
        ('core', '0005_alter_taxrate_unique_together_fxgainlossaccount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arpayment',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Approval workflow status', max_length=20),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_payments_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer making the payment', null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.customer'),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='reference',
            field=models.CharField(blank=True, help_text='Payment reference number', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total payment amount', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='arpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DEPRECATED: Use total_amount instead', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='arpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use allocations instead', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_legacy', to='ar.arinvoice'),
        ),
        migrations.CreateModel(
            name='ARPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount allocated to this invoice', max_digits=14)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='ar.arinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ar.arpayment')),
            ],
            options={
                'db_table': 'ar_arpaymentallocation',
                'unique_together': {('payment', 'invoice')},
            },
        ),
    ]
