# Generated by Django 5.2.7 on 2025-10-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0005_set_default_payment_status'),
        ('ar', '0008_alter_arpayment_options_arinvoice_approval_status_and_more'),
    ]

    operations = [
    ]
