# Generated by Django 5.2.7 on 2025-10-17 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0010_arinvoice_subtotal_arinvoice_tax_amount_and_more'),
        ('core', '0005_alter_taxrate_unique_together_fxgainlossaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arpaymentallocation',
            name='current_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate from invoice currency to payment currency at allocation time', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='arpaymentallocation',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the invoice (copied from invoice at allocation time)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_payment_allocations_invoice_currency', to='core.currency'),
        ),
    ]
