# Generated by Django 5.2.7 on 2025-10-17 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0011_add_allocation_currency_fields'),
        ('core', '0005_alter_taxrate_unique_together_fxgainlossaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arpayment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate from invoice currency to payment currency (for FX gain/loss)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the invoice(s) being paid - for FX tracking', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_payments_invoice_currency', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='arpayment',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Payment currency (currency received)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_payments_currency', to='core.currency'),
        ),
    ]
