# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount being approved', max_digits=15)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Instance',
                'verbose_name_plural': 'Approval Instances',
                'db_table': 'approval_approvalinstance',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Order in which this step is executed')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum amount that triggers this step', max_digits=15)),
                ('approver_type', models.CharField(choices=[('USER', 'Specific Users'), ('GROUP', 'User Group'), ('ROLE', 'Role-based'), ('MANAGER', "Requestor's Manager"), ('COST_CENTER_MANAGER', 'Cost Center Manager'), ('PROJECT_MANAGER', 'Project Manager')], default='USER', max_length=30)),
                ('role_name', models.CharField(blank=True, help_text='Role name for role-based approval', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this step must be completed')),
                ('require_all_approvers', models.BooleanField(default=False, help_text='Require all approvers or just one')),
                ('sla_hours', models.PositiveIntegerField(blank=True, help_text='SLA in hours for this approval step', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to='auth.group')),
                ('approvers', models.ManyToManyField(blank=True, related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Step',
                'verbose_name_plural': 'Approval Steps',
                'db_table': 'approval_approvalstep',
                'ordering': ['workflow', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStepInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approval_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_instances', to='approvals.approvalinstance')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='approvals.approvalstep')),
            ],
            options={
                'verbose_name': 'Approval Step Instance',
                'verbose_name_plural': 'Approval Step Instances',
                'db_table': 'approval_approvalstepinstance',
                'ordering': ['approval_instance', 'workflow_step__sequence'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DELEGATED', 'Delegated'), ('RETURNED', 'Returned for Revision')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('step_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalstepinstance')),
            ],
            options={
                'verbose_name': 'Approval Action',
                'verbose_name_plural': 'Approval Actions',
                'db_table': 'approval_approvalaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(help_text="Model path (e.g., 'requisition.PRHeader')", max_length=100)),
                ('scope', models.CharField(choices=[('HEADER', 'Header Level'), ('LINE', 'Line Item Level'), ('BOTH', 'Both Header and Line')], default='HEADER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_parallel_approval', models.BooleanField(default=False, help_text='Allow multiple approvers to approve simultaneously')),
                ('require_all_approvers', models.BooleanField(default=True, help_text='Require all approvers in a step or just one')),
                ('auto_approve_below_threshold', models.BooleanField(default=False, help_text='Auto-approve if amount is below all thresholds')),
                ('min_approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum amount requiring approval', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
                'db_table': 'approval_approvalworkflow',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='approvals.approvalworkflow'),
        ),
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount delegate can approve', max_digits=15, null=True)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, help_text='Leave blank to delegate all workflows', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='approvals.approvalworkflow')),
            ],
            options={
                'verbose_name': 'Approval Delegation',
                'verbose_name_plural': 'Approval Delegations',
                'db_table': 'approval_approvaldelegation',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('COST_CENTER', 'Cost Center'), ('PROJECT', 'Project')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('fiscal_year', models.PositiveIntegerField()),
                ('fiscal_period', models.PositiveIntegerField(blank=True, help_text='Leave blank for annual budget', null=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Total allocated budget', max_digits=15)),
                ('pre_committed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='PRs submitted but not approved', max_digits=15)),
                ('committed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Approved PRs and open POs', max_digits=15)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual spending (AP invoices)', max_digits=15)),
                ('allow_overrun', models.BooleanField(default=False, help_text='Allow spending beyond allocated budget')),
                ('warning_threshold_pct', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Warning threshold percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget Allocation',
                'verbose_name_plural': 'Budget Allocations',
                'db_table': 'approval_budgetallocation',
                'ordering': ['-fiscal_year', '-fiscal_period'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'fiscal_year'], name='approval_bu_entity__f6842c_idx')],
                'unique_together': {('entity_type', 'entity_id', 'fiscal_year', 'fiscal_period')},
            },
        ),
        migrations.CreateModel(
            name='BudgetCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('check_type', models.CharField(choices=[('PRE_COMMIT', 'Pre-Commitment'), ('COMMIT', 'Commitment'), ('ACTUAL', 'Actual')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('passed', models.BooleanField()),
                ('message', models.TextField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('budget_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='approvals.budgetallocation')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_checks_performed', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Budget Check',
                'verbose_name_plural': 'Budget Checks',
                'db_table': 'approval_budgetcheck',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('workflow', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='approval_ap_content_76320d_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['status', 'requested_at'], name='approval_ap_status_d8f5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetcheck',
            index=models.Index(fields=['content_type', 'object_id'], name='approval_bu_content_5f2583_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetcheck',
            index=models.Index(fields=['passed', 'checked_at'], name='approval_bu_passed_58ce0d_idx'),
        ),
    ]
