# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('adjustment_date', models.DateField(default=django.utils.timezone.now)),
                ('adjustment_type', models.CharField(choices=[('CYCLE_COUNT', 'Cycle Count'), ('PHYSICAL_COUNT', 'Physical Inventory Count'), ('DAMAGE', 'Damage/Loss'), ('OBSOLETE', 'Obsolescence'), ('CORRECTION', 'Data Correction'), ('WRITE_OFF', 'Write-off'), ('FOUND', 'Found Inventory')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'db_table': 'inventory_stock_adjustment',
                'ordering': ['-adjustment_date', '-adjustment_number'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('system_quantity', models.DecimalField(decimal_places=4, help_text='Quantity per system', max_digits=15)),
                ('physical_quantity', models.DecimalField(decimal_places=4, help_text='Actual counted quantity', max_digits=15)),
                ('adjustment_quantity', models.DecimalField(decimal_places=4, help_text='Difference (Physical - System)', max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('adjustment_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'inventory_stock_adjustment_line',
                'ordering': ['adjustment', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Goods Receipt'), ('PURCHASE_RETURN', 'Return from Purchase'), ('TRANSFER_IN', 'Transfer In'), ('PRODUCTION_IN', 'Production Receipt'), ('ADJUSTMENT_IN', 'Adjustment Increase'), ('ISSUE', 'Inventory Issue'), ('SALES_RETURN', 'Sales Return'), ('TRANSFER_OUT', 'Transfer Out'), ('PRODUCTION_OUT', 'Production Issue'), ('ADJUSTMENT_OUT', 'Adjustment Decrease'), ('SCRAP', 'Scrap/Write-off')], max_length=20)),
                ('movement_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('lot_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('serial_numbers', models.JSONField(blank=True, default=list)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'inventory_stock_movement',
                'ordering': ['-movement_date', '-movement_number'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('actual_received_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'db_table': 'inventory_stock_transfer',
                'ordering': ['-transfer_date', '-transfer_number'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('serial_numbers', models.JSONField(blank=True, default=list)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'inventory_stock_transfer_line',
                'ordering': ['transfer', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Physical quantity available', max_digits=15)),
                ('quantity_reserved', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Quantity reserved for orders', max_digits=15)),
                ('quantity_in_transit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Quantity being transferred', max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Current average unit cost', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('last_movement_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='catalog.catalogitem')),
            ],
            options={
                'verbose_name': 'Inventory Balance',
                'verbose_name_plural': 'Inventory Balances',
                'db_table': 'inventory_balance',
                'ordering': ['warehouse', 'catalog_item'],
            },
        ),
    ]
