# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('receiving', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybalance',
            name='storage_location',
            field=models.ForeignKey(blank=True, help_text='Specific bin location (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='receiving.storagelocation'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='receiving.warehouse'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='receiving.warehouse'),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustment'),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='catalog_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='catalog.catalogitem'),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='receiving.storagelocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='catalog_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.catalogitem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='receiving.storagelocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='receiving.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='receiving.storagelocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='receiving.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='receiving.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='receiving.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='catalog_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='catalog.catalogitem'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines_out', to='receiving.storagelocation'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines_in', to='receiving.storagelocation'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktransfer'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['catalog_item', 'warehouse'], name='inventory_b_catalog_3a4654_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['warehouse', 'quantity_on_hand'], name='inventory_b_warehou_13fe86_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['lot_number'], name='inventory_b_lot_num_a38feb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorybalance',
            unique_together={('catalog_item', 'warehouse', 'storage_location', 'lot_number')},
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['status', 'adjustment_date'], name='inventory_s_status_6ea160_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['warehouse', 'status'], name='inventory_s_warehou_04e0b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockadjustmentline',
            unique_together={('adjustment', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'movement_date'], name='inventory_s_movemen_d3e574_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['catalog_item', 'movement_date'], name='inventory_s_catalog_51c22f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['from_warehouse', 'movement_date'], name='inventory_s_from_wa_44ef37_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['to_warehouse', 'movement_date'], name='inventory_s_to_ware_eaa9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_85b37c_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status', 'transfer_date'], name='inventory_s_status_941d69_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['from_warehouse', 'status'], name='inventory_s_from_wa_023b22_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['to_warehouse', 'status'], name='inventory_s_to_ware_499340_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktransferline',
            unique_together={('transfer', 'line_number')},
        ),
    ]
