# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Category code (e.g., COMP, FURN)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight Line'), ('DECLINING_BALANCE', 'Declining Balance'), ('UNITS_OF_PRODUCTION', 'Units of Production'), ('SUM_OF_YEARS', 'Sum of Years Digits')], default='STRAIGHT_LINE', max_length=20)),
                ('useful_life_years', models.DecimalField(blank=True, decimal_places=2, help_text='Default useful life in years', max_digits=5, null=True)),
                ('salvage_value_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default salvage value as % of cost', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'assets_category',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Purchase Invoice'), ('WARRANTY', 'Warranty Document'), ('MANUAL', 'User Manual'), ('CERTIFICATE', 'Certificate'), ('PHOTO', 'Photo'), ('INSURANCE', 'Insurance Document'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='asset_documents/%Y/%m/')),
                ('file_url', models.URLField(blank=True, help_text='External URL if document is stored elsewhere')),
                ('document_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Document',
                'verbose_name_plural': 'Asset Documents',
                'db_table': 'assets_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Location code', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Location name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, choices=[('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('EG', 'Egypt'), ('IN', 'India')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Location',
                'verbose_name_plural': 'Asset Locations',
                'db_table': 'assets_location',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive Maintenance'), ('CORRECTIVE', 'Corrective Maintenance'), ('REPAIR', 'Repair'), ('INSPECTION', 'Inspection'), ('UPGRADE', 'Upgrade')], max_length=20)),
                ('description', models.TextField(help_text='Description of maintenance performed')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_capitalized', models.BooleanField(default=False, help_text='Should this cost be capitalized to asset?')),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('vendor_invoice', models.CharField(blank=True, max_length=100)),
                ('downtime_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Hours asset was unavailable', max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Maintenance',
                'verbose_name_plural': 'Asset Maintenance Records',
                'db_table': 'assets_maintenance',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('reason', models.TextField(help_text='Reason for transfer')),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Transfer',
                'verbose_name_plural': 'Asset Transfers',
                'db_table': 'assets_transfer',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(help_text='Month/period for this depreciation')),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_book_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Depreciation Schedule',
                'verbose_name_plural': 'Depreciation Schedules',
                'db_table': 'assets_depreciation_schedule',
                'ordering': ['asset', 'period_date'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(help_text='Unique asset number', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Asset name/description', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, help_text='Serial/VIN number', max_length=100)),
                ('acquisition_date', models.DateField(help_text='Date asset was acquired')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, help_text='Original acquisition cost', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight Line'), ('DECLINING_BALANCE', 'Declining Balance'), ('UNITS_OF_PRODUCTION', 'Units of Production'), ('SUM_OF_YEARS', 'Sum of Years Digits')], max_length=20)),
                ('useful_life_years', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('depreciation_start_date', models.DateField(help_text='Date to start calculating depreciation')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DISPOSED', 'Disposed'), ('RETIRED', 'Retired'), ('UNDER_MAINTENANCE', 'Under Maintenance')], default='DRAFT', max_length=20)),
                ('capitalization_date', models.DateField(blank=True, help_text='Date asset was capitalized', null=True)),
                ('total_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_book_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('last_depreciation_date', models.DateField(blank=True, null=True)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_method', models.CharField(blank=True, choices=[('SALE', 'Sale'), ('SCRAP', 'Scrap'), ('DONATION', 'Donation'), ('TRADE_IN', 'Trade-In'), ('OTHER', 'Other')], max_length=50)),
                ('disposal_proceeds', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('disposal_notes', models.TextField(blank=True)),
                ('purchase_order', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accumulated_depreciation_account', models.ForeignKey(help_text='Accumulated depreciation account', on_delete=django.db.models.deletion.PROTECT, related_name='assets_accum_dep', to='segment.xx_segment')),
                ('asset_account', models.ForeignKey(help_text='Asset GL account', on_delete=django.db.models.deletion.PROTECT, related_name='assets_asset', to='segment.xx_segment')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets_asset',
                'ordering': ['-acquisition_date', 'asset_number'],
            },
        ),
    ]
