# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ap', '0002_initial'),
        ('fixed_assets', '0001_initial'),
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        ('periods', '__first__'),
        ('segment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='capitalization_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capitalized_assets', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.currency'),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_expense_account',
            field=models.ForeignKey(help_text='Depreciation expense account', on_delete=django.db.models.deletion.PROTECT, related_name='assets_dep_exp', to='segment.xx_segment'),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposal_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposed_assets', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_supplied', to='ap.supplier'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='accumulated_depreciation_account',
            field=models.ForeignKey(blank=True, help_text='Default accumulated depreciation account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories_accum_dep', to='segment.xx_segment'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='asset_account',
            field=models.ForeignKey(blank=True, help_text='Default asset GL account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories_asset', to='segment.xx_segment'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='depreciation_expense_account',
            field=models.ForeignKey(blank=True, help_text='Default depreciation expense account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories_dep_exp', to='segment.xx_segment'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='fixed_assets.assetcategory'),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fixed_assets.asset'),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_asset_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_locations_custodian', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='parent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_locations', to='fixed_assets.assetlocation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='fixed_assets.assetlocation'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fixed_assets.asset'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_maintenance', to='core.currency'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='fixed_assets.asset'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='fixed_assets.assetlocation'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='fixed_assets.assetlocation'),
        ),
        migrations.AddField(
            model_name='depreciationschedule',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_schedules', to='fixed_assets.asset'),
        ),
        migrations.AddField(
            model_name='depreciationschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_depreciation_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depreciationschedule',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_entries', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='depreciationschedule',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Fiscal period for this depreciation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_schedules', to='periods.fiscalperiod'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_number'], name='assets_asse_asset_n_5a20c7_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_asse_status_347ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category', 'location'], name='assets_asse_categor_f8c89d_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationschedule',
            index=models.Index(fields=['period_date', 'is_posted'], name='assets_depr_period__49a048_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='depreciationschedule',
            unique_together={('asset', 'period_date')},
        ),
    ]
