# Generated by Django 5.2.7 on 2025-11-10 15:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.BooleanField(default=True, help_text='Ensures only one configuration record exists', unique=True)),
                ('minimum_capitalization_amount', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Minimum amount for an asset to be capitalized (items below this are expensed)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('auto_generate_asset_number', models.BooleanField(default=True, help_text='Automatically generate asset numbers')),
                ('asset_number_prefix', models.CharField(default='ASSET-', help_text='Prefix for auto-generated asset numbers', max_length=10)),
                ('next_asset_number', models.IntegerField(default=1, help_text='Next sequential number for asset numbering')),
                ('auto_calculate_depreciation', models.BooleanField(default=True, help_text='Automatically calculate depreciation monthly')),
                ('depreciation_posting_day', models.IntegerField(default=1, help_text='Day of month to post depreciation (1-28)', validators=[django.core.validators.MinValueValidator(1)])),
                ('require_capitalization_approval', models.BooleanField(default=False, help_text='Require approval before capitalizing assets')),
                ('require_disposal_approval', models.BooleanField(default=True, help_text='Require approval before disposing assets')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_asset_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Configuration',
                'verbose_name_plural': 'Asset Configuration',
                'db_table': 'assets_configuration',
            },
        ),
    ]
