# Generated by Django 5.2.7 on 2025-11-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('fixed_assets', '0003_assetconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetconfiguration',
            name='base_currency',
            field=models.ForeignKey(blank=True, help_text='Base currency for the minimum capitalization amount', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_config_base_currency', to='core.currency'),
        ),
    ]
