# Generated by Django 5.2.7 on 2025-11-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0003_initial'),
        ('fixed_assets', '0004_assetconfiguration_base_currency'),
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ap_invoice',
            field=models.ForeignKey(blank=True, help_text='AP Invoice that created this asset (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to='ap.apinvoice'),
        ),
        migrations.AddField(
            model_name='asset',
            name='ap_invoice_line',
            field=models.IntegerField(blank=True, help_text='Line number in AP Invoice', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='grn',
            field=models.ForeignKey(blank=True, help_text='GRN that created this asset (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to='receiving.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='asset',
            name='grn_line',
            field=models.ForeignKey(blank=True, help_text='GRN Line that created this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset', to='receiving.grnline'),
        ),
        migrations.AddField(
            model_name='asset',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('AP_INVOICE', 'AP Invoice'), ('GRN', 'Goods Receipt Note'), ('PO', 'Purchase Order')], default='MANUAL', help_text='Source of asset creation', max_length=20),
        ),
    ]
