# Generated by Django 5.2.7 on 2025-11-10 17:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0005_asset_ap_invoice_asset_ap_invoice_line_asset_grn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcategory',
            name='depreciation_expense_account',
        ),
        migrations.RemoveField(
            model_name='assetcategory',
            name='salvage_value_percent',
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='major',
            field=models.CharField(blank=True, help_text='Major category classification', max_length=100),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='min_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum value for capitalization', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='minor',
            field=models.CharField(blank=True, help_text='Minor category classification', max_length=100),
        ),
    ]
