# Generated by Django 5.2.7 on 2025-11-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0006_remove_assetcategory_depreciation_expense_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcategory',
            name='accumulated_depreciation_account',
        ),
    ]
