# Generated by Django 5.2.7 on 2025-11-10 21:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('fixed_assets', '0007_remove_assetcategory_accumulated_depreciation_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('CIP', 'cip'), ('CAPITALIZED', 'capitalized'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='AssetAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_date', models.DateField()),
                ('adjustment_type', models.CharField(choices=[('COST', 'Cost Adjustment'), ('USEFUL_LIFE', 'Useful Life Adjustment'), ('DEPRECIATION', 'Manual Depreciation Adjustment'), ('RECATEGORIZE', 'Recategorization')], max_length=20)),
                ('old_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cost_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('old_useful_life', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_useful_life', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('depreciation_adjustment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to adjust depreciation by', max_digits=15, null=True)),
                ('reason', models.TextField(help_text='Reason for adjustment')),
                ('notes', models.TextField(blank=True)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_approvals', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='fixed_assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_adjustments', to='finance.journalentry')),
                ('new_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_to', to='fixed_assets.assetcategory')),
                ('old_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_from', to='fixed_assets.assetcategory')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Adjustment',
                'verbose_name_plural': 'Asset Adjustments',
                'db_table': 'assets_adjustment',
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetRetirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retirement_date', models.DateField(help_text='Date of retirement')),
                ('retirement_type', models.CharField(choices=[('SALE', 'Sale'), ('SCRAP', 'Scrap'), ('DONATION', 'Donation'), ('TRADE_IN', 'Trade-In'), ('LOSS', 'Loss/Theft'), ('TRANSFER_OUT', 'Transfer Out'), ('OTHER', 'Other')], max_length=20)),
                ('net_book_value_at_retirement', models.DecimalField(decimal_places=2, help_text='NBV at retirement date', max_digits=15)),
                ('disposal_proceeds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Proceeds from disposal', max_digits=15)),
                ('disposal_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costs incurred for disposal', max_digits=15)),
                ('gain_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gain or loss on disposal', max_digits=15)),
                ('buyer_recipient', models.CharField(blank=True, help_text='Who received the asset', max_length=255)),
                ('sale_invoice_number', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(help_text='Reason for retirement')),
                ('notes', models.TextField(blank=True)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retirement_approvals', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retirements', to='fixed_assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retirements', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_retirements', to='finance.journalentry')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retirement_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Retirement',
                'verbose_name_plural': 'Asset Retirements',
                'db_table': 'assets_retirement',
                'ordering': ['-retirement_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('CAPITALIZE', 'Capitalization'), ('RETIRE', 'Retirement'), ('ADJUST', 'Adjustment'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('request_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='fixed_assets.assetadjustment')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='fixed_assets.asset')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_approval_reviews', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='fixed_assets.assettransfer')),
                ('retirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='fixed_assets.assetretirement')),
            ],
            options={
                'verbose_name': 'Asset Approval',
                'verbose_name_plural': 'Asset Approvals',
                'db_table': 'assets_approval',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'operation_type'], name='assets_appr_status_d59aee_idx')],
            },
        ),
    ]
