# Generated by Django 5.2.7 on 2025-11-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0008_alter_asset_status_assetadjustment_assetretirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
