"""
Django migration for PR to PO conversion workflow updates.

This migration:
1. Updates PRLine model with new conversion tracking fields
2. Creates PRToPOLineMapping model for many-to-many relationship
3. Updates POHeader to use ManyToMany for source_pr_headers
4. Removes old pr_line_id from POLine

Run with: python manage.py makemigrations requisitions
Then: python manage.py migrate
"""

# Note: This is a reference file. The actual migration will be generated by Django.
# Run: python manage.py makemigrations requisitions purchase_orders

# Changes summary:
# 
# PRLine model:
# - Remove: converted_to_po (BooleanField)
# - Remove: po_reference (CharField)
# - Add: conversion_status (CharField with choices)
# - Add: quantity_converted (DecimalField)
#
# New model: PRToPOLineMapping
# - pr_line (ForeignKey to PRLine)
# - po_line (ForeignKey to POLine)
# - quantity_converted (DecimalField)
# - created_at (DateTimeField)
# - created_by (ForeignKey to User)
# - notes (TextField)
#
# POHeader model:
# - Remove: pr_header_id (IntegerField)
# - Remove: pr_number (CharField)
# - Add: source_pr_headers (ManyToManyField to PRHeader)
#
# POLine model:
# - Remove: pr_line_id (IntegerField)
# - Access PR lines through: po_line.pr_line_mappings.all()
