# Generated by Django 5.2.7 on 2025-10-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('finance', '0014_alter_invoice_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
