# Generated by Django 5.2.7 on 2025-11-08 13:25

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('item_description', models.TextField()),
                ('specifications', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('CATEGORIZED', 'Categorized - Linked to Catalog'), ('NON_CATEGORIZED', 'Non-Categorized - Free Text')], default='NON_CATEGORIZED', help_text='Whether item is linked to catalog or is free text', max_length=20)),
                ('vendor_part_number', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price in transaction currency', max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Line total in transaction currency', max_digits=15)),
                ('base_currency_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price in base currency', max_digits=15)),
                ('base_currency_line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total in base currency', max_digits=15)),
                ('need_by_date', models.DateField(blank=True, null=True)),
                ('quantity_received', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('quantity_billed', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PO Line',
                'verbose_name_plural': 'PO Lines',
                'db_table': 'procurement_poline',
                'ordering': ['po_header', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='POHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('po_date', models.DateField(default=datetime.date.today)),
                ('po_type', models.CharField(choices=[('CATEGORIZED_GOODS', 'Categorized Goods'), ('UNCATEGORIZED_GOODS', 'Uncategorized Goods'), ('SERVICES', 'Services')], default='UNCATEGORIZED_GOODS', help_text='Type of PO: Categorized Goods, Uncategorized Goods, or Services', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('CONFIRMED', 'Confirmed/Sent to Vendor'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Fully Received'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('vendor_name', models.CharField(blank=True, help_text='Vendor/Supplier name', max_length=200)),
                ('vendor_email', models.EmailField(blank=True, max_length=254)),
                ('vendor_phone', models.CharField(blank=True, max_length=50)),
                ('vendor_reference', models.CharField(blank=True, help_text="Vendor's quote/reference number", max_length=100)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_contact', models.CharField(blank=True, max_length=200)),
                ('delivery_phone', models.CharField(blank=True, max_length=50)),
                ('delivery_status', models.CharField(choices=[('NOT_RECEIVED', 'Not Received'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Fully Received')], db_index=True, default='NOT_RECEIVED', help_text='Tracks the delivery/receiving status of the PO', max_length=20)),
                ('payment_terms', models.CharField(choices=[('NET_30', 'Net 30'), ('NET_60', 'Net 60'), ('NET_90', 'Net 90'), ('COD', 'Cash on Delivery'), ('CIA', 'Cash in Advance'), ('DUE_ON_RECEIPT', 'Due on Receipt')], default='NET_30', max_length=20)),
                ('payment_terms_description', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal in transaction currency', max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax in transaction currency', max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount in transaction currency', max_digits=15)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping in transaction currency', max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total in transaction currency', max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate from transaction currency to base currency', max_digits=15)),
                ('base_currency_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal in base currency', max_digits=15)),
                ('base_currency_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount in base currency', max_digits=15)),
                ('cost_center_code', models.CharField(blank=True, max_length=50)),
                ('cost_center_name', models.CharField(blank=True, max_length=200)),
                ('project_code', models.CharField(blank=True, max_length=50)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_approved', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_cancelled', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(help_text='Transaction currency', on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'procurement_poheader',
                'ordering': ['-po_date', '-po_number'],
            },
        ),
    ]
