# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('purchase_orders', '0001_initial'),
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poheader',
            name='source_pr_headers',
            field=models.ManyToManyField(blank=True, help_text='Source PR Headers that contribute to this PO', related_name='converted_pos', to='requisitions.prheader'),
        ),
        migrations.AddField(
            model_name='poheader',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poline',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.catalogitem'),
        ),
        migrations.AddField(
            model_name='poline',
            name='po_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase_orders.poheader'),
        ),
        migrations.AddField(
            model_name='poline',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unitofmeasure'),
        ),
        migrations.AddIndex(
            model_name='poheader',
            index=models.Index(fields=['po_number'], name='procurement_po_numb_db2629_idx'),
        ),
        migrations.AddIndex(
            model_name='poheader',
            index=models.Index(fields=['status'], name='procurement_status_5572be_idx'),
        ),
        migrations.AddIndex(
            model_name='poheader',
            index=models.Index(fields=['vendor_name'], name='procurement_vendor__429b40_idx'),
        ),
        migrations.AddIndex(
            model_name='poheader',
            index=models.Index(fields=['po_date'], name='procurement_po_date_1b2937_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='poline',
            unique_together={('po_header', 'line_number')},
        ),
    ]
