# Generated by Django 5.2.7 on 2025-10-09 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_currency_options_and_more'),
        ('finance', '0012_alter_account_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('POSTED', 'POSTED'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=16)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_invoices', to='core.currency')),
                ('gl_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_source_new', to='finance.journalentry')),
            ],
            options={
                'db_table': 'ap_apinvoice',
            },
        ),
        migrations.CreateModel(
            name='APItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_country', models.CharField(blank=True, choices=[('AE', 'UAE'), ('SA', 'KSA'), ('EG', 'Egypt'), ('IN', 'India')], max_length=2, null=True)),
                ('tax_category', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('ZERO', 'Zero'), ('EXEMPT', 'Exempt'), ('RC', 'Reverse Charge')], max_length=16, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ap.apinvoice')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_items', to='core.taxrate')),
            ],
            options={
                'db_table': 'ap_apitem',
            },
        ),
        migrations.CreateModel(
            name='APPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled', models.BooleanField(default=False)),
                ('reconciliation_ref', models.CharField(blank=True, max_length=64)),
                ('reconciled_at', models.DateField(blank=True, null=True)),
                ('payment_fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_payments', to='finance.bankaccount')),
                ('gl_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_payment_source_new', to='finance.journalentry')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ap.apinvoice')),
            ],
            options={
                'db_table': 'ap_appayment',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Unique supplier code', max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(default='AE', help_text='ISO 2-letter country code', max_length=2)),
                ('vat_number', models.CharField(blank=True, help_text='VAT/Tax registration number', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(blank=True, help_text="Supplier's default currency", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_suppliers', to='core.currency')),
            ],
            options={
                'db_table': 'ap_supplier',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ap.supplier'),
        ),
    ]
