# Generated by Django 5.2.7 on 2025-10-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apinvoice',
            name='base_currency_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount in base currency', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate used when posting (invoice currency to base currency)', max_digits=18, null=True),
        ),
    ]
