# Generated by Django 5.2.7 on 2025-10-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0002_apinvoice_base_currency_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apinvoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Whether invoice is cancelled'),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='is_posted',
            field=models.BooleanField(default=False, help_text='Whether invoice is posted to GL'),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', help_text='Payment status of the invoice', max_length=20),
        ),
        migrations.AlterField(
            model_name='apinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('POSTED', 'POSTED'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=16, null=True),
        ),
    ]
