# Generated by Django 5.2.7 on 2025-11-08 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ap', '0002_initial'),
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        ('periods', '__first__'),
        ('purchase_orders', '0002_initial'),
        ('receiving', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apinvoice',
            name='goods_receipt',
            field=models.ForeignKey(blank=True, help_text='Goods Receipt linked to this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_invoices', to='receiving.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Fiscal period for this invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_invoices', to='periods.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='po_header',
            field=models.ForeignKey(blank=True, help_text='Purchase Order linked to this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_invoices', to='purchase_orders.poheader'),
        ),
        migrations.AddField(
            model_name='apitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ap.apinvoice'),
        ),
        migrations.AddField(
            model_name='apitem',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_items', to='core.taxrate'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_payments', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Payment currency (currency paid)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_payments_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='gl_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_payment_source_new', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use allocations instead', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_legacy', to='ap.apinvoice'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the invoice(s) being paid - for FX tracking', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_payments_invoice_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Fiscal period for this payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_payments', to='periods.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='appaymentallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='ap.apinvoice'),
        ),
        migrations.AddField(
            model_name='appaymentallocation',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the invoice (copied from invoice at allocation time)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_payment_allocations_invoice_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='appaymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ap.appayment'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.ForeignKey(blank=True, help_text="Supplier's default currency", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_suppliers', to='core.currency'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier receiving the payment', null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.supplier'),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ap.supplier'),
        ),
        migrations.AddField(
            model_name='vendorcontact',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ap.supplier'),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vendor_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ap.supplier'),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vendor_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendoronboardingchecklist',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendoronboardingchecklist',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ap.vendordocument'),
        ),
        migrations.AddField(
            model_name='vendoronboardingchecklist',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_checklist', to='ap.supplier'),
        ),
        migrations.AddField(
            model_name='vendorperformancerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorperformancerecord',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='ap.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='appaymentallocation',
            unique_together={('payment', 'invoice')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorperformancerecord',
            unique_together={('vendor', 'period_start', 'period_end')},
        ),
    ]
