# Generated by Django 5.2.7 on 2025-11-12 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0003_initial'),
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apinvoiceglline',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='APInvoiceDistributionSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='ap.apinvoiceglline')),
                ('segment', models.ForeignKey(help_text='Specific segment value', on_delete=django.db.models.deletion.PROTECT, to='segment.xx_segment')),
                ('segment_type', models.ForeignKey(help_text='Segment type (Account, Department, etc.)', on_delete=django.db.models.deletion.PROTECT, to='segment.xx_segmenttype')),
            ],
            options={
                'db_table': 'ap_invoice_distribution_segment',
                'ordering': ['segment_type__segment_id'],
                'unique_together': {('distribution', 'segment_type')},
            },
        ),
    ]
