# Generated by Django 5.2.7 on 2025-10-14 06:53

from django.db import migrations


def migrate_status_forward(apps, schema_editor):
    """Convert old status field to new separated fields"""
    APInvoice = apps.get_model('ap', 'APInvoice')
    
    for invoice in APInvoice.objects.all():
        if invoice.status == 'POSTED':
            invoice.is_posted = True
            invoice.payment_status = 'UNPAID'
        elif invoice.status == 'PAID':
            invoice.is_posted = True
            invoice.payment_status = 'PAID'
        elif invoice.status == 'CANCELLED':
            invoice.is_cancelled = True
            invoice.is_posted = False  # Cancelled invoices are not posted
            invoice.payment_status = 'UNPAID'
        else:  # DRAFT or None
            invoice.is_posted = False
            invoice.payment_status = 'UNPAID'
        
        invoice.save(update_fields=['is_posted', 'payment_status', 'is_cancelled'])


def migrate_status_backward(apps, schema_editor):
    """Convert new fields back to old status field"""
    APInvoice = apps.get_model('ap', 'APInvoice')
    
    for invoice in APInvoice.objects.all():
        if invoice.is_cancelled:
            invoice.status = 'CANCELLED'
        elif invoice.payment_status == 'PAID':
            invoice.status = 'PAID'
        elif invoice.is_posted:
            invoice.status = 'POSTED'
        else:
            invoice.status = 'DRAFT'
        
        invoice.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0003_apinvoice_cancelled_at_apinvoice_is_cancelled_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_status_forward, migrate_status_backward),
    ]
