# Generated by Django 5.2.7 on 2025-11-13 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0004_alter_apinvoiceglline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apinvoiceglline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distribution amount', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apinvoiceglline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apinvoiceglline',
            name='description',
            field=models.CharField(blank=True, help_text='Description of this distribution', max_length=500),
        ),
        migrations.AddField(
            model_name='apinvoiceglline',
            name='invoice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='ap.apinvoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apinvoiceglline',
            name='line_type',
            field=models.CharField(default='distribution', help_text='Type of GL line', max_length=50),
        ),
        migrations.AddField(
            model_name='apinvoiceglline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='apinvoiceglline',
            table='ap_invoice_distribution',
        ),
    ]
