# Generated by Django 5.2.7 on 2025-10-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0005_remove_apinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apinvoice',
            name='country',
            field=models.CharField(choices=[('AE', 'UAE'), ('SA', 'KSA'), ('EG', 'Egypt'), ('IN', 'India')], default='AE', help_text='Tax country for this invoice (defaults to supplier country)', max_length=2),
        ),
    ]
