# Generated by Django 5.2.7 on 2025-10-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0006_apinvoice_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='appayment',
            name='memo',
            field=models.CharField(blank=True, help_text='Payment memo/notes', max_length=255),
        ),
    ]
