# Generated by Django 5.2.7 on 2025-10-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0005_set_default_payment_status'),
        ('ap', '0008_alter_appayment_options_apinvoice_approval_status_and_more'),
    ]

    operations = [
    ]
