# Generated by Django 5.2.7 on 2025-10-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0009_merge_20251016_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='apinvoice',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Invoice subtotal (before tax)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total tax amount', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Invoice total (subtotal + tax)', max_digits=14, null=True),
        ),
    ]
