# Generated by Django 5.2.7 on 2025-11-08 13:25

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ap', '0002_initial'),
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('purchase_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('annual_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cost_centers', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='requisitions.costcenter')),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
                'db_table': 'requisition_costcenter',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PRHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('pr_date', models.DateField(default=datetime.date.today)),
                ('required_date', models.DateField(help_text='Date by which items are needed')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('business_justification', models.TextField(blank=True, help_text='Explain why this purchase is necessary')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('pr_type', models.CharField(choices=[('CATEGORIZED_GOODS', 'Categorized Goods'), ('UNCATEGORIZED_GOODS', 'Uncategorized Goods'), ('SERVICES', 'Services')], default='UNCATEGORIZED_GOODS', help_text='Type of purchase requisition: Categorized Goods, Uncategorized Goods, or Services', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted to PO'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('budget_check_passed', models.BooleanField(default=False)),
                ('budget_check_message', models.TextField(blank=True)),
                ('budget_checked_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_suggestions_generated', models.BooleanField(default=False)),
                ('can_split_by_vendor', models.BooleanField(default=True, help_text='Allow splitting this PR into multiple POs by vendor')),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_prs', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_prs', to=settings.AUTH_USER_MODEL)),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_prs', to=settings.AUTH_USER_MODEL)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pr_headers', to='requisitions.costcenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prs', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pr_headers', to='core.currency')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_prs', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_prs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Requisition',
                'verbose_name_plural': 'Purchase Requisitions',
                'db_table': 'requisition_prheader',
                'ordering': ['-pr_date', '-pr_number'],
            },
        ),
        migrations.CreateModel(
            name='PRLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('item_description', models.CharField(max_length=500)),
                ('specifications', models.TextField(blank=True, help_text='Detailed specifications or requirements')),
                ('item_type', models.CharField(choices=[('CATEGORIZED', 'Categorized - Linked to Catalog'), ('NON_CATEGORIZED', 'Non-Categorized - Free Text')], default='NON_CATEGORIZED', help_text='Whether item is linked to catalog or is free text', max_length=20)),
                ('suggested_catalog_items', models.JSONField(blank=True, default=list, help_text='AI/system-suggested catalog items')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('estimated_unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('tax_code', models.CharField(blank=True, help_text='Tax code (e.g., VAT-STANDARD, GST-5)', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate in percentage', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('need_by_date', models.DateField(help_text='Date by which this item is needed')),
                ('gl_account', models.CharField(blank=True, help_text='GL account code for this expense', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('conversion_status', models.CharField(choices=[('NOT_CONVERTED', 'Not Converted'), ('PARTIALLY_CONVERTED', 'Partially Converted'), ('FULLY_CONVERTED', 'Fully Converted')], default='NOT_CONVERTED', help_text='Track conversion status of this PR line', max_length=20)),
                ('quantity_converted', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Quantity already converted to PO', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_lines', to='catalog.catalogitem')),
                ('pr_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='requisitions.prheader')),
                ('suggested_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_pr_lines', to='ap.supplier')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pr_lines', to='catalog.unitofmeasure')),
            ],
            options={
                'verbose_name': 'PR Line',
                'verbose_name_plural': 'PR Lines',
                'db_table': 'requisition_prline',
                'ordering': ['pr_header', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'requisition_project',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='prheader',
            name='project',
            field=models.ForeignKey(blank=True, help_text='For capital expenditures or project-based purchasing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pr_headers', to='requisitions.project'),
        ),
        migrations.CreateModel(
            name='PRToPOLineMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_converted', models.DecimalField(decimal_places=4, help_text='Quantity from PR line converted to this PO line', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this conversion (e.g., split reason)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_to_po_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('po_line', models.ForeignKey(help_text='Target PO line', on_delete=django.db.models.deletion.CASCADE, related_name='pr_line_mappings', to='purchase_orders.poline')),
                ('pr_line', models.ForeignKey(help_text='Source PR line', on_delete=django.db.models.deletion.PROTECT, related_name='po_line_mappings', to='requisitions.prline')),
            ],
            options={
                'verbose_name': 'PR to PO Line Mapping',
                'verbose_name_plural': 'PR to PO Line Mappings',
                'db_table': 'requisition_pr_to_po_line_mapping',
                'ordering': ['pr_line', 'po_line'],
            },
        ),
        migrations.AddIndex(
            model_name='prline',
            index=models.Index(fields=['catalog_item'], name='requisition_catalog_29b926_idx'),
        ),
        migrations.AddIndex(
            model_name='prline',
            index=models.Index(fields=['suggested_supplier'], name='requisition_suggest_40dfb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prline',
            unique_together={('pr_header', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='prheader',
            index=models.Index(fields=['status', 'pr_date'], name='requisition_status_08d6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='prheader',
            index=models.Index(fields=['cost_center', 'status'], name='requisition_cost_ce_54e3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='prheader',
            index=models.Index(fields=['project', 'status'], name='requisition_project_d2339a_idx'),
        ),
        migrations.AddIndex(
            model_name='prtopolinemapping',
            index=models.Index(fields=['pr_line'], name='requisition_pr_line_55b962_idx'),
        ),
        migrations.AddIndex(
            model_name='prtopolinemapping',
            index=models.Index(fields=['po_line'], name='requisition_po_line_763588_idx'),
        ),
    ]
